services:
  - type: web
    name: htn-lyrics
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GENIUS_ACCESS_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
