services:
  - type: web
    name: htn-lyrics
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GENIUS_ACCESS_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: PUBLIC_URL
        sync: false
      - key: SCRAPERAPI_KEY
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
